# Site settings
title: 
header-img: img/home-bg.png
email: johannkerr@gmail.com
copyright_name: johann
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: johannkerr
github_username:  johann
learn_profile: johann
email_username: johannkerr@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
